"""Module to store functionality for data transformation."""
import numpy as np
import pandas as pd


def create_ohlc_features(frame: pd.DataFrame) -> pd.DataFrame:
    """Function to create various features for the OHLC data."""
    df = frame.copy()
    df.columns = df.columns.str.upper()
    multiplier = 2

    # Features
    df["OC"] = df["CLOSE"] / df["OPEN"] - 1
    df["HC"] = df["HIGH"] / df["LOW"] - 1
    df["GAP"] = df["OPEN"] / df["CLOSE"].shift(1) - 1
    df["RET"] = np.log(df["CLOSE"] / df["CLOSE"].shift(1))

    for i in [7, 14, 28]:
        df["PCHG" + str(i)] = df["CLOSE"].pct_change(i)
        df["VCHG" + str(i)] = df["VOLUME"].pct_change(i)
        df["RET" + str(i)] = df["RET"].rolling(i).sum()
        df["MA" + str(i)] = df["CLOSE"] / df["CLOSE"].rolling(i).mean()
        df["VMA" + str(i)] = df["VOLUME"] / df["VOLUME"].rolling(i).mean()
        df["OC " + str(i)] = df["OC"].rolling(i).mean()
        df["HC " + str(i)] = df["HC"].rolling(i).mean()
        df["GAP " + str(i)] = df["GAP"].rolling(i).mean()
        df["STD " + str(i)] = df["RET"].rolling(i).std()
        df["UB " + str(i)] = (
            df["CLOSE"].rolling(i).mean() + df["CLOSE"].rolling(i).std() * multiplier
        )
        df["LB " + str(i)] = (
            df["CLOSE"].rolling(i).mean() - df["CLOSE"].rolling(i).std() * multiplier
        )

    # Tomorrow's close price > 99.5% of today's close price
    df["LABEL"] = np.where(df["CLOSE"].shift(-1) > 1.0005 * df["CLOSE"], 1, 0)

    # Drop rows with NaNs generated by rolling/shift operations
    df = df.dropna()

    return df


def correlated_features(df: pd.DataFrame, threshold: float = 0.9):
    """Remove the first feature that is correlated with any other feature."""

    col_corr = set()
    corr_matrix = df.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
